name: Test

on:
  push:
    branches:
    - main
  pull_request:
    #schedule:
    # monthly
    #- cron: "0 0 1 * *"

env:
  #bump to clear caches
  ACTION_CACHE_VERSION: 'v1'

jobs:
  # download deps, check dependabot's pom.xml is up-to-date
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
          key: ${{ env.ACTION_CACHE_VERSION }}-${{ runner.os }}-maven-${{ hashFiles('**/deps.edn') }}
      - name: Prepare java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@9.5
        with:
          cli: 1.10.3.1087
      - name: Check dependabot is in sync with project.clj
        run: ./script/check-dependabot
  # example test matrix
  test:
    needs: setup
    strategy:
      matrix:
        java: ['8', '11', '17']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
          key: ${{ env.ACTION_CACHE_VERSION }}-${{ runner.os }}-maven-${{ hashFiles('**/deps.edn') }}
      - name: Prepare java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@9.5
        with:
          cli: 1.10.3.1087
      - run: clojure -Xtest
